Use dompurify to sanitize presentation content output
manywho/ui-bootstrap pull request #171
Opened 2020-09-30 14:51 UTC by ianhaycox

Ensure any user entered input has dangerous Javascript removed before rendering in the presentation components.

For example,

<img src="x" onerror=alert(1) />

converts to,

<img src="x">

See https://github.com/cure53/DOMPurify for details.

2020-10-05 10:18 UTC, jamesbrattBoomi requested changes
Looks good to me. Only thing I'm hesitant about is making this the default behaviour. I know for example that GoG have iframes embedded in presentations. Would they get stripped out by dompurify?
My feeling is, is that we should ship this not as default behaviour, but to then conduct the impact analysis before adjusting the default accordingly.

2020-10-06 10:01 UTC, dshoulders approved these changes
Looks like this should resolve the problem. I'd also be wary of making this default behaviour. 
Longer term I'd feel happier if we are able to remove any instances of dangerouslySetInnerHTML, perhaps using something like https://github.com/remarkjs/react-markdown.

2020-10-08 11:23 UTC, ianhaycox commented
After discussions with Rick and Calvin, it has been decided to change the default to allow scripting so we don't break customers.
However - the default player has been modified to prevent scripting by default https://github.com/manywho/ui-html5/pull/58  This is to try to ensure new customers/flows are protected from XSS attacks out of the box.
Generally it is expected that most production Flows do not use the default Player, so customers will need to enable the disableScripting setting in their custom players to be safe.

2020-10-09 12:55 UTC, jamesbrattBoomi approved these changes

2020-10-29 16:50 UTC, merged